server:
  port: 8080

spring:
  application:
    name: pokecenter-hoenn

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/pokecenter

pokecenter-hoenn:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

  integrations:
    pokemon-league:
      base-url: ${POKEMON_LEAGUE_BASE_URL:http://localhost:8081}
      timeout:
        connect: 5000
        read: 10000

logging:
  level:
    com.hoenn.pokecenter: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
